### ISSUE TITLE
Personal Finance Tracker

### ISSUE THREAD

**Issue by Ahasasjain** [Vikash-8090-Yadav/Future.WebNet#326]
### Project title
Personal Finance tracker

### Project Description
it is a web app that helps the user to keep track of daily expenses.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes
please assign me this issue.
<hr/>
