### ISSUE TITLE
Personal Finance Tracker

### ISSUE THREAD

**Issue by Ahasasjain** [Vikash-8090-Yadav/Future.WebNet#327]
### Project title
Personal Finance Tracker

### Project Description
It's a web app that helps the user to keep track of their daily expenses.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes
Please Assign me this project @Vikash-8090-Yadav
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this
