### ISSUE TITLE
Want to add a To-Do list in frontend projects

### ISSUE THREAD

**Issue by rayarka26** [Vikash-8090-Yadav/Future.WebNet#336]
### Project title
To-Do List

### Project Description
Having details to things to be done

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC'23
<hr/>

**Comment by rayarka26** [comment]
I will make a to-do-list which will be storing new items and we can strike of any item which we feel to remove. It will be good designed. We will not be deleting the items we will strike the items not needed just like a real list. A little different from general to-do-list.

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this

**Comment by Manish12-verma** [comment]
hey Please assign this issue to me
